{% set version = "0.7.3" %}

package:
  name: pcaspy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pcaspy/pcaspy-{{ version }}.tar.gz
  sha256: 82f72f21293dc450bea5bec7beb69da6e5232425c1dc07524c3dba8a096bd555
  patches:
    # the pypi tarball is built by conda-build on linux, so we need to undo a patch
    # that should only have been applied for linux builds, see
    # https://github.com/paulscherrerinstitute/pcaspy/blob/69fa94055838e8a7fbbc6dffaf97f535493dbf85/conda-recipe/readline.patch
    - readline.patch  # [win]

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv  # [not win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - epics-base 3
    - pip
    - python
    - setuptools
    - swig
  run:
    - epics-base
    - python

test:
  imports:
    - pcaspy
    - pcaspy.alarm
    - pcaspy.cas
    - pcaspy.driver
    - pcaspy.tools
  requires:
    - numpy
  source_files:
    - test/gddTest.py
  commands:
    - python test/gddTest.py

about:
  home: https://github.com/paulscherrerinstitute/pcaspy/wiki
  doc_url: https://pcaspy.readthedocs.io/
  dev_url: https://github.com/paulscherrerinstitute/pcaspy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Portable Channel Access Server in Python
  description: |
    PCASpy provides not only the low level python binding to
    EPICS Portable Channel Access Server but also the necessary
    high level abstraction to ease the server tool programming.

extra:
  recipe-maintainers:
    - duncanmmacleod
