{% set version = "0.8.0" %}

package:
  name: pcaspy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pcaspy/pcaspy-{{ version }}.tar.gz
  sha256: 4f3cafdedc552acc9d9208a9c146e2da10b5e20942d4e401c907244d32ffc72c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - epics-base 3
    - pip
    - python
    - setuptools
    - swig
  run:
    - epics-base
    - python

test:
  requires:
    - numpy
    - pip
  imports:
    - pcaspy
    - pcaspy.alarm
    - pcaspy.cas
    - pcaspy.driver
    - pcaspy.tools
  source_files:
    - test/gddTest.py
  commands:
    # check metadata
    - python -m pip check
    - python -m pip show pcaspy
    # run tests
    - python test/gddTest.py

about:
  home: https://github.com/paulscherrerinstitute/pcaspy/wiki
  doc_url: https://pcaspy.readthedocs.io/
  dev_url: https://github.com/paulscherrerinstitute/pcaspy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Portable Channel Access Server in Python
  description: |
    PCASpy provides not only the low level python binding to
    EPICS Portable Channel Access Server but also the necessary
    high level abstraction to ease the server tool programming.

extra:
  recipe-maintainers:
    - duncanmmacleod
